### ISSUE TITLE
How can i use diy url?

### ISSUE THREAD

**Issue by yw0nam** [Akaisorani/pixiv-crawler#4]
Thanks for great work.
All most every function works well, but dl_diy_urls function doesn't work.
I tried 
```
url = """https://www.pixiv.net/en/tags/%E9%BB%92%E9%AB%AA/illustrations?
order=popular_male_d&mode=safe&s_mode=s_tag&type=illust"""
pc.dl_diy_urls([url],10)
```
(%E9%BB%92%E9%AB%AA　means 黒髪)

but my output is my url as blue string.

https://www.pixiv.net/en/tags/%E9%BB%92%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust 

I guess the string means that url can't read.
In this case, how can i fix this problem?

**Comment by yw0nam** [comment]
Okay, i managed it, Thanks for good Codes and Notations

**Comment by Akaisorani** [comment]
@yw0nam 
Thanks for your report.
The problem is that I handled all diy_urls as same as daily_rank. However, in your case it should be handled as tag search.
Now I have fixed it. Please install the latest version.
Have fun.

**Comment by yw0nam** [comment]
@Akaisorani 
Thanks for respond my issue.
I tried latest version, and it works perfect for me.
I hope my issue helped you improve your code.
once more, Thanks for great work!

**Comment by yw0nam** [comment]
First, I'm sorry about reopen issue.. 
I think it works well, but still, it has something wrong.

Pixiv Searching option is this.
tag: 銀髪(silver hair)
target:only illustrations
order: sort by popularity(male)
Age: All ages

I tried this code
```
url = "https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust"
pc.dl_diy_urls(url,150 , deep_into_manga=True)
```
When i tried above code, it works.
But when i checked save directory by this code, i found something strange.

```
temp =glob(directory_path/DIY_url)
print(temp)  #temp value is 80
```
I think, temp value should be at least 150
I guess this problem caused by line 201 at scraper_manga.py.

`else: newclsf.append((clsf_name,item_list))`

**Comment by Akaisorani** [comment]
> First, I'm sorry about reopen issue..
> I think it works well, but still, it has something wrong.
> 
> Pixiv Searching option is this.
> tag: 銀髪(silver hair)
> target:only illustrations
> order: sort by popularity(male)
> Age: All ages
> 
> I tried this code
> 
> ```
> url = "https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust"
> pc.dl_diy_urls(url,150 , deep_into_manga=True)
> ```
> 
> When i tried above code, it works.
> But when i checked save directory by this code, i found something strange.
> 
> ```
> temp =glob(directory_path/DIY_url)
> print(temp)  #temp value is 80
> ```
> 
> I think, temp value should be at least 150
> I guess this problem caused by line 201 at scraper_manga.py.
> 
> `else: newclsf.append((clsf_name,item_list))`

The url, `'https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust'`, actually link to only the first page of the tag search result. There are only 60 illustrations in one page.
This is easy to solve.
You can add option `p=` which identify the page number. Here is an example:
```
url_list=["https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust&p=1",
"https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust&p=2",
"https://www.pixiv.net/tags/%E9%8A%80%E9%AB%AA/illustrations?order=popular_male_d&mode=safe&s_mode=s_tag&type=illust&p=3"
]
pc.dl_diy_urls(url_list,150,deep_into_manga=True)
```

**Comment by yw0nam** [comment]
Thanks for very quick response and advise. 
Now it works just what i want! once again, thanks for great work!!
