### ISSUE TITLE
Have you test it on VPS ?

### ISSUE THREAD

**Issue by kathynguyen333** [Akaisorani/pixiv-crawler#6]
I had tested it from pc , it worked . However , when i try it on VPS . it\s doesnt work . Can you fix it?

**Comment by Akaisorani** [comment]
@kathynguyen333 
It works on my VPS for a long time. Your VPS IP may be checked and need a captcha when log in. You can copy your cookies.txt file from your pc to the VPS and try it again.
Can you provide more information (config and error message)?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akaisorani/pixiv-crawler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 上午10:38
收件人:&nbsp;"Akaisorani/pixiv-crawler"<pixiv-crawler@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Akaisorani/pixiv-crawler] Have you test it on VPS ? (#6)





 
I had tested it from pc , it worked . However , when i try it on VPS . it\s doesnt work . Can you fix it?

**Comment by kathynguyen333** [comment]
> @kathynguyen333 It works on my VPS for a long time. Your VPS IP may be checked and need a captcha when log in. You can copy your cookies.txt file from your pc to the VPS and try it again. Can you provide more information (config and error message)?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Akaisorani/pixiv-crawler" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月3日(星期一) 上午10:38 收件人:&nbsp;"Akaisorani/pixiv-crawler"<pixiv-crawler@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Akaisorani/pixiv-crawler] Have you test it on VPS ? (#6) I had tested it from pc , it worked . However , when i try it on VPS . it\s doesnt work . Can you fix it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kathynguyen333** [comment]
> @kathynguyen333 It works on my VPS for a long time. Your VPS IP may be checked and need a captcha when log in. You can copy your cookies.txt file from your pc to the VPS and try it again. Can you provide more information (config and error message)?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Akaisorani/pixiv-crawler" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月3日(星期一) 上午10:38 收件人:&nbsp;"Akaisorani/pixiv-crawler"<pixiv-crawler@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Akaisorani/pixiv-crawler] Have you test it on VPS ? (#6) I had tested it from pc , it worked . However , when i try it on VPS . it\s doesnt work . Can you fix it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry i click

**Comment by kathynguyen333** [comment]
Tks you! it worked .
